[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle SPA routing - redirect all paths to index.html so that React Router works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 