[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing - redirect all paths to index.html so that React Router works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 